const db = require('./db.js')
const express=require('./express.js')
const auth=require('./auth/index.js')
const placementofficer = require('./placement-officer/index.js')
const student = require('./student/index.js')